// generated by stringer -type LeadType,LeadArch,LeadOS,LeadSignatureType -output lead_string.go; DO NOT EDIT

package rpm

import "fmt"

const _LeadType_name = "LeadTypeBinaryLeadTypeSource"

var _LeadType_index = [...]uint8{0, 14, 28}

func (i LeadType) String() string {
	if i < 0 || i >= LeadType(len(_LeadType_index)-1) {
		return fmt.Sprintf("LeadType(%d)", i)
	}
	return _LeadType_name[_LeadType_index[i]:_LeadType_index[i+1]]
}

const (
	_LeadArch_name_0 = "LeadArchI386_x86_64LeadArchAlpha_Sparc64LeadArchSparcLeadArchMIPSLeadArchPowerPCLeadArch68000LeadArchSGILeadArchRS6000LeadArchIA64LeadArchSparc64LeadArchMIPSelLeadArchARMLeadArchMiNTLeadArchS_390LeadArchS_390xLeadArchPowerPC64LeadArchSuperHLeadArchXtensa"
	_LeadArch_name_1 = "LeadArchNoarch"
)

var (
	_LeadArch_index_0 = [...]uint8{0, 19, 40, 53, 65, 80, 93, 104, 118, 130, 145, 159, 170, 182, 195, 209, 226, 240, 254}
	_LeadArch_index_1 = [...]uint8{0, 14}
)

func (i LeadArch) String() string {
	switch {
	case 1 <= i && i <= 18:
		i -= 1
		return _LeadArch_name_0[_LeadArch_index_0[i]:_LeadArch_index_0[i+1]]
	case i == 255:
		return _LeadArch_name_1
	default:
		return fmt.Sprintf("LeadArch(%d)", i)
	}
}

const _LeadOS_name = "LeadOSLinuxLeadOSIrixLeadOSSolarisLeadOSSunOSAmigaOSHP_UXOSF1FreeBSDSCO_SVIrix64NextStepBSD_OSmachtenCYGWIN32_NTCYGWIN32_95UNIX_SVMiNTOS_390VM_ESALinux_390Darwin"

var _LeadOS_index = [...]uint8{0, 11, 21, 34, 45, 52, 57, 61, 68, 74, 80, 88, 94, 101, 112, 123, 130, 134, 140, 146, 155, 161}

func (i LeadOS) String() string {
	i -= 1
	if i < 0 || i >= LeadOS(len(_LeadOS_index)-1) {
		return fmt.Sprintf("LeadOS(%d)", i+1)
	}
	return _LeadOS_name[_LeadOS_index[i]:_LeadOS_index[i+1]]
}

const _LeadSignatureType_name = "LeadSignatureTypeHeaderSignature"

var _LeadSignatureType_index = [...]uint8{0, 32}

func (i LeadSignatureType) String() string {
	i -= 5
	if i < 0 || i >= LeadSignatureType(len(_LeadSignatureType_index)-1) {
		return fmt.Sprintf("LeadSignatureType(%d)", i+5)
	}
	return _LeadSignatureType_name[_LeadSignatureType_index[i]:_LeadSignatureType_index[i+1]]
}
